from pydantic import BaseModel, Field
from .meta import CVEMeta, PatchMeta
from .llm_resp import FunctionInfoList, InitSecInfo


class SemanticDesc(BaseModel):
    funcs_desc: FunctionInfoList = Field(
        # From the functional extraction
        default_factory=FunctionInfoList,
        description="Info extracted from functional extraction",
    )
    # From the security extraction
    sec_desc: InitSecInfo = Field(
        default_factory=InitSecInfo, description="Info extracted from sec extraction"
    )


class CVEDescription(BaseModel):
    """
    The integrated description of a CVE and will be saved in the database.
    """

    cve_meta: CVEMeta = Field(
        default_factory=CVEMeta, description="Metadata parsed from CVE desc file"
    )
    desc: SemanticDesc = Field(
        default_factory=SemanticDesc, description="Intergrated info generated by LLM"
    )
